package practicejava;
public class findTheElementThatAppearsOnes {
	public static void main(String[] args) {
		int arr[]= {1,2,3,2,1};		//HERE WE HAD TAKEN AN ARRAY
		int X=0; 		//XOR VALUE 
		for(int i=0;i<arr.length;i++) { 		//HERE THIS FOR LOOP IS UESD TO PRINT ALL THE ARRAY
			X=X ^ arr[i];		//HERE IT IS THE XOR 9EXCLUSIVE OR) OPERATION AND IT IS A BITWISE OPERATOR IT IS UESD IF BITS ARE DIFFERENT =1 AND IF THE BITS ARE SAME RESULT =0
								//SO IN THE EVERY ELEMENT OF ARRAY IS CHANGED INTO BINARY NUMBER AND CONVERTED BINARY NUMBER SHOULD NOT BE REPEATED SO THE THE UNIQUE ONE IS APPERED ONES
		}
		System.out.println("IN THE ARRAY THE ELEMENT APPERED ONES IS : " +X);
	}

}
